version: '3.8'
services:
  postgres:
    image: 'postgres:15.5'
    env_file: .env
    # environment:
    #   - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    # volumes:
    #   - ./posgres_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  rabbitmq:
    image: rabbitmq:3.13.7-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"
  
  